name: Build and deploy React + PHP app to Azure Web App - catalogo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🟡 1. Instalar Node y construir React
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm install

      - name: Build React app
        run: npm run build
        env:
          CI: false  # Desactiva modo CI para que los warnings no rompan el build

      - name: Move React build files to root
        run: |
          rm -rf src node_modules package.json package-lock.json
          mv build/* ./ 2>/dev/null || true
          rm -rf build

      # 🟣 2. Instalar PHP si es necesario
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer install --prefer-dist --no-progress

      # 📦 3. Empaquetar todo para desplegar
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-react-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: php-react-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'catalogo' # Cambia si tu App Service tiene otro nombre
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
