name: Build and deploy React + PHP app to Azure Web App - catalogo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---- Instala Node y construye el frontend ----
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Move React build to root
        run: |
          rm -rf src node_modules package.json package-lock.json
          mv build/* ./
          rm -rf build

      # ---- Setup PHP si se usa composer.json ----
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer install --prefer-dist --no-progress

      # ---- Crear ZIP con frontend + backend ----
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FFDE54E637A4453A81A71E01514CD742 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D34EA54A6F2D43CC8FBA9DC29D6D751A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_74F35DF002924B9689B186327AB3398A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'catalogo'
          slot-name: 'Production'
          package: .
